### PR TITLE
sync with upstream 225afcf

### PR DESCRIPTION
**Pull request by notspiff**

### CODE REVIEW

**Comment by Montellese** [comment]
You'll have to remove the second commit as it's already part of my fork.

BTW thanks for doing the tedious work (again).

**Comment by notspiff** [comment]
git should really just prune it as i picked it from your branch. but i guess it changed slightly due to the c++ stuff in front. i cannot remove it as it influence the same stuff as the other commits. i'll see if a reorder fixes it.

**Comment by notspiff** [comment]
stupid thing. rebased on your branch, should be fine now.

**Comment by Montellese** [comment]
Thanks.

**Pull request merged**
